### ISSUE TITLE
Change `writtenIn` to `transpiler`

### ISSUE THREAD

**Issue by unional** [unional/domture#2]
`{ writtenIn: 'ts' }` is an abstraction that aims to provide an abstraction to the more complicated systemjs config. 
Using `plugin-typescript` as an example: https://github.com/frankwallis/plugin-typescript#setup

Explore the idea of changing this to `transpiler` so that it is more straightforward for user who understands `systemjs` (which they need to anyway if they want to have more custom configuration).

Also, explore on how to specify transpiler options (A unified `transpilerOptions` for both ts and babel or separate `typescriptOptions`/`babelOptions` as in `systemjs`).

**Comment by pallavi16** [comment]
Hi, 
I have been working on this issue for quite sometime. I am not quite clear with what this issue is about.  I could see that in src/systemjsConfig.ts, there is a module with writtenIn. Does this issue require this module to be changed to  transpiler by utilizing the plugin-typescript?

**Comment by unional** [comment]
It's not about using `plugin-typescript`. The link is about how it design the configuration. 

This idea to explore in this issue is about how to expose the configuration that is easy to use and understand by the user.

**Comment by pallavi16** [comment]
Thanks for your swift response. 
Yes I understand that. But as it is mentioned in the issue that writtenIn provides an abstraction to more complicated systemjsConfig. Does it mean tweaking/modifying the systemjsConfig in specific?

**Comment by unional** [comment]
Yes, as you can see here: https://github.com/unional/domture/blob/89094db29f89ecb951d09c215a420bb9faf117dd/src/systemjsConfig.ts#L42-L63

This is what needs to be done if configuring systemjsConfig directly.

So some abstraction is still needed. :)

**Comment by unional** [comment]
Since deciding what config to expose can be complicated (although we can model after `plugin-typescript`), the first step is to change `writtenIn: 'ts'` to `transpiler: 'typescript'` and make sure all tests still pass.

**Comment by pallavi16** [comment]
Yes, thank you for your suggestion. I will work on it and try to see if the tests pass. :)
